add vault-config

diff --git a/ci-templates.yml b/ci-templates.yml
--- a/ci-templates.yml
+++ b/ci-templates.yml
@@ -2,19 +2,19 @@
   before_script:
     - apk add --no-cache curl jq unzip
     - |
-      # Installation de Vault client
       curl -o vault.zip https://releases.hashicorp.com/vault/1.13.0/vault_1.13.0_linux_amd64.zip
       unzip vault.zip
       mv vault /usr/local/bin/
-      export VAULT_ADDR="${VAULT_ADDR}"
-      export VAULT_TOKEN="${VAULT_TOKEN}"
+      # Check Vault connection
+      curl -s $VAULT_ADDR/v1/sys/health || (echo "Vault server is not reachable at $VAULT_ADDR" && exit 1)
       # Authenticate with Vault
-      vault login $VAULT_TOKEN
-      # Obtention des secrets depuis Vault
-      export DOCKER_USERNAME="$(vault kv get -field=DOCKER_USERNAME secret/pitstopsecrets )"
-      export DOCKER_HUB_PASSWORD="$(vault kv get -field=DOCKER_HUB_PASSWORD secret/pitstopsecrets)"
-      export GITHUB_TOKEN="$(vault kv get -field=GITHUB_TOKEN secret/pitstopsecrets )"
-      export GITLAB_TOKEN="$(vault kv get -field=GITLAB_TOKEN secret/pitstopsecrets )"
+      vault login $VAULT_TOKEN || (echo "Vault authentication failed" && exit 1)
+      # Fetch secrets
+      export DOCKER_USERNAME="$(vault kv get -field=DOCKER_USERNAME secret/pitstopsecrets || exit 1)"
+      export DOCKER_HUB_PASSWORD="$(vault kv get -field=DOCKER_HUB_PASSWORD secret/pitstopsecrets || exit 1)"
+      export GITHUB_TOKEN="$(vault kv get -field=GITHUB_TOKEN secret/pitstopsecrets || exit 1)"
+      export GITLAB_TOKEN="$(vault kv get -field=GITLAB_TOKEN secret/pitstopsecrets || exit 1)"
+
 
 .build-template:
   image: docker:latest
