add vault-config

diff --git a/ci-templates.yml b/ci-templates.yml
--- a/ci-templates.yml
+++ b/ci-templates.yml
@@ -1,30 +1,20 @@
 .vault-config: &vault-config
   before_script:
-    - apk add --no-cache curl jq unzip
-    - |
-      # Download and set up Vault CLI
-      curl -o vault.zip https://releases.hashicorp.com/vault/1.13.0/vault_1.13.0_linux_amd64.zip
-      unzip vault.zip
-      mv vault /usr/local/bin/
-      
-      # Check Vault connection
-      echo "Checking Vault server connectivity at $VAULT_ADDR"
-      curl -s $VAULT_ADDR/v1/sys/health || (echo "Vault server is not reachable at $VAULT_ADDR" && exit 1)
-      
-      # Authenticate with Vault
-      echo "Authenticating with Vault..."
-      vault login $VAULT_TOKEN || (echo "Vault authentication failed" && exit 1)
-      
-      # Fetch secrets
-      echo "Fetching secrets from Vault..."
-      export DOCKER_USERNAME="$(vault kv get -field=DOCKER_USERNAME secret/pitstopsecrets || exit 1)"
-      export DOCKER_HUB_PASSWORD="$(vault kv get -field=DOCKER_HUB_PASSWORD secret/pitstopsecrets || exit 1)"
-      export GITHUB_TOKEN="$(vault kv get -field=GITHUB_TOKEN secret/pitstopsecrets || exit 1)"
-      export GITLAB_TOKEN="$(vault kv get -field=GITLAB_TOKEN secret/pitstopsecrets || exit 1)"
+    - echo "Checking Vault server connectivity at $VAULT_ADDR"
+    - curl -s $VAULT_ADDR/v1/sys/health || (echo "Vault server is not reachable at $VAULT_ADDR" && exit 1)
+
+    - echo "Authenticating with Vault..."
+    - vault login $VAULT_TOKEN || (echo "Vault authentication failed" && exit 1)
+
+    - echo "Fetching secrets from Vault..."
+    - export DOCKER_USERNAME="$(vault kv get -field=DOCKER_USERNAME secret/pitstopsecrets || exit 1)"
+    - export DOCKER_HUB_PASSWORD="$(vault kv get -field=DOCKER_HUB_PASSWORD secret/pitstopsecrets || exit 1)"
+    - export GITHUB_TOKEN="$(vault kv get -field=GITHUB_TOKEN secret/pitstopsecrets || exit 1)"
+    - export GITLAB_TOKEN="$(vault kv get -field=GITLAB_TOKEN secret/pitstopsecrets || exit 1)"
 
 
 .build-template:
-  image: docker:latest
+  image: hashicorp/vault:latest
   services:
     - docker:dind
   variables:
